spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: false
    validate-on-migrate: true
  application:
    name: backend_for_arctic_team

  datasource:
    url: jdbc:postgresql://postgres:5432/arctic_team?currentSchema=public
    username: postgres
    password: egor

  data:
    redis:
      host: redis-cache
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  redis:
    host: redis-cache
    port: 6379
jwt:
  secret: ${JWT_SECRET:X7k9p2mN4rT8vB5wQ1yL6cJ3hF0aD8gE5sW2zU7oR4tY1iP9}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

logging:
  level:
    com.arctic.backend_for_arctic_team: TRACE
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG


charts:
  service:
    url: http://python-service:8000


management:
  endpoints:
    web:
      exposure:
        include: health,info
        exclude: env,beans,mappings


